In [1]:
import numpy as np

In [2]:
numpy_array=np.array([1,2,3,4])

In [3]:
numpy_array

array([1, 2, 3, 4])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [16]:
oneD_array=np.arange(15)

In [17]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
twoD_array=oneD_array.reshape(3,5)

In [19]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
threeD_array=np.arange(27).reshape(3,3,3)

In [21]:
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
np.array(24)

array(24)

In [23]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [24]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
array=np.array([[[[1,2,3,4],[2,3,6,7]],[5,4,7,5],[1,9,8,5]]])

C:\Users\IDEAL COM\AppData\Local\Temp\ipykernel_2244\3703924665.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array=np.array([[[[1,2,3,4],[2,3,6,7]],[5,4,7,5],[1,9,8,5]]])


In [28]:
array.shape

(1, 3)

In [29]:
array

array([[list([[1, 2, 3, 4], [2, 3, 6, 7]]), list([5, 4, 7, 5]),
        list([1, 9, 8, 5])]], dtype=object)

In [30]:
arr1=np.array([x for x in range(1,10)])

In [31]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.array([x for x in range(1,13)])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
arr3D=np.array([x for x in range(1,13)]).reshape(3,2,2)

In [38]:
arr3D

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [36]:
np.array([x for x in range(1,13)]).reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr3D.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Arithematic Operation

In [41]:
A=np.array([[1,2,3,4],[5,6,7,8]])
B=np.array([3,4,2,1])

In [42]:
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
B

array([3, 4, 2, 1])

In [44]:
np.add(A,B)

array([[ 4,  6,  5,  5],
       [ 8, 10,  9,  9]])

In [45]:
np.subtract(A,B)

array([[-2, -2,  1,  3],
       [ 2,  2,  5,  7]])

In [46]:
np.multiply(A,B)

array([[ 3,  8,  6,  4],
       [15, 24, 14,  8]])

In [48]:
np.divide(A,B)

array([[0.33333333, 0.5       , 1.5       , 4.        ],
       [1.66666667, 1.5       , 3.5       , 8.        ]])

In [49]:
np.power(A,2)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [50]:
np.power(A,B)

array([[   1,   16,    9,    4],
       [ 125, 1296,   49,    8]])

In [53]:
x=np.array([i for i in range(10)])

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
condlist=[x<5,x>5]
choicelist=([x**2,x**3])

In [57]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [59]:
arr=np.array([[1,5,7],[3,7,11],[11,5,9]])

In [60]:
arr

array([[ 1,  5,  7],
       [ 3,  7, 11],
       [11,  5,  9]])

In [61]:
np.amin(arr)

1

In [62]:
np.amin(arr,axis=0)

array([1, 5, 7])

In [63]:
np.amin(arr,axis=1)

array([1, 3, 5])

In [64]:
np.amax(arr)

11

In [65]:
np.amax(arr,axis=0)

array([11,  7, 11])

In [67]:
np.amax(arr,axis=1)

array([ 7, 11, 11])

In [68]:
np.mean(arr)

6.555555555555555

In [69]:
np.median(arr)

7.0

In [70]:
np.std(arr)

3.235604395235786

In [71]:
np.var(arr)

10.469135802469134

In [72]:
np.percentile(arr,25)

5.0

In [73]:
np.percentile(arr,50)

7.0

In [74]:
np.percentile(arr,75)

9.0

In [75]:
deg=np.array([0,30,45,60,90])

In [76]:
deg

array([ 0, 30, 45, 60, 90])

In [78]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [79]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [80]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [81]:
np.arccos(deg*np.pi/180)

C:\Users\IDEAL COM\AppData\Local\Temp\ipykernel_2244\3660325324.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(deg*np.pi/180)


array([1.57079633, 1.01972674, 0.66745722,        nan,        nan])

In [82]:
np.arcsin(deg*np.pi/180)

C:\Users\IDEAL COM\AppData\Local\Temp\ipykernel_2244\2079635364.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(deg*np.pi/180)


array([0.        , 0.55106958, 0.90333911,        nan,        nan])

In [83]:
np.arctan(deg*np.pi/180)

array([0.        , 0.48234791, 0.66577375, 0.80844879, 1.00388482])

In [84]:
np.array([2.5,-1.6,5,6,9,10.3])

array([ 2.5, -1.6,  5. ,  6. ,  9. , 10.3])

In [85]:
np.floor(np.array([2.5,-1.6,5,6,9,10.3]))

array([ 2., -2.,  5.,  6.,  9., 10.])

In [86]:
np.ceil([np.array([2.5,-1.6,5,6,9,10.3])])

array([[ 3., -1.,  5.,  6.,  9., 11.]])

In [89]:
array_1d=np.array([1,4,6,8])
array_2d=np.array([[1,6,4],[7,8,3]])
array_3d=np.array([[[1,4,8],[1,8,9]],[11,3,6],[12,5,8]])

C:\Users\IDEAL COM\AppData\Local\Temp\ipykernel_2244\2393647754.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_3d=np.array([[[1,4,8],[1,8,9]],[11,3,6],[12,5,8]])


In [90]:
array_1d

array([1, 4, 6, 8])

In [91]:
array_2d

array([[1, 6, 4],
       [7, 8, 3]])

In [92]:
array_3d

array([list([[1, 4, 8], [1, 8, 9]]), list([11, 3, 6]), list([12, 5, 8])],
      dtype=object)

In [93]:
array_1d[0]

1

In [94]:
array_1d[3]

8

In [95]:
array_1d[-3]

4

In [96]:
array_2d[0,2]

4

In [97]:
array_2d[1,1]

8

In [103]:
array_1d[0:]

array([1, 4, 6, 8])

In [105]:
array_1d[-3:]

array([4, 6, 8])

In [106]:
array_2d[0,1:3]

array([6, 4])

In [107]:
array_2d[1,-3:]

array([7, 8, 3])